- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repo
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - import_tasks: tasks/packages.yml
#    - import_tasks: tasks/docker_config.yml
