- hosts: localhost
  connection: local
  become: true

  pre-tasks:
    - name: update repo
      apt:
	update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/docker_config.yml
